Changelog++ for v0.17.1
hashicorp/vault-plugin-secrets-azure pull request #186
Opened 2024-04-03 14:21 UTC by tomhjp

Prepare for v0.17.1 release which will be published to the releases website too.

The only changes are dep updates to satisfy the security scanner:

```shell-session
$ scan binary bin/vault-plugin-secrets-azure
✓ Scanned file:{path:"bin/vault-plugin-secrets-azure"} in 14.5s - no results found
```

2024-04-03 14:25 UTC, tomhjp commented
I missed #181 when I was checking for changelog updates - perhaps this should be v0.18.0 given the change? @MilenaHC are you happy with the changelog notice I've written for that?

2024-04-16 16:35 UTC, Zlaticanin approved these changes
LGTM! Sorry about the late approval, just now saw this.

2024-04-17 21:24 UTC, vinay-gopalan requested changes
Can we add in a line for the bug fix similar to #192? Thanks!

2024-04-30 16:02 UTC, vinay-gopalan approved these changes

2024-04-30 17:00 UTC, merged